spring:
  datasource:
    url: ENC(ZCqUOPrSLwTL9Aptjjl5/rzFVZ5BDJSD2+5to8aAZnr2UphLawMmE5QkPwXcolgq+mGBLntY9Yksfyxw1TDFlA==)
    username: ENC(2dwq/1A3Izar5AxsXgp+uRKmyBN4NWkK)
    password: ENC(dJT0HkQvDEYOFPbdvlxo3Epaat/czOph)
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1800000  # 连接最大寿命 30min
      connection-timeout: 1800000  # 连接超时时间 30min
      minimum-idle: 100   # 最小空闲连接数
      maximum-pool-size: 200  # 最大连接池大小
      connection-test-query: "select 1"
      idle-timeout: 600000 # 空闲连接超时时长 10min
jasypt:
  encryptor:
    password: your_grace
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
